import type { GridColDef } from "@mui/x-data-grid";

import CurrencyCell from "../shared/CurrencyCell";
import YearMonthCell from "../shared/YearMonthCell";
import { PropertyIncomeExpenseSummaryRow } from "./types";

export const propertyIncomeExpenseSummaryColumns: GridColDef<PropertyIncomeExpenseSummaryRow>[] =
  [
    {
      field: "yearMonth",
      headerName: "年月",
      headerClassName: "align-right-header",
      width: 100,
      editable: false,
      sortable: false,
      filterable: false,
    },
    {
      field: "expectedAmount1",
      headerName: "本来入金額",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true}/>,
    },
    {
      field: "managementCompanyAmount1",
      headerName: "管理会社入金",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true} />,
    },
    {
      field: "difference1",
      headerName: "差額",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true} showNotZeroBackgroundColor={true} />,
    },
    {
      field: "expectedAmount2",
      headerName: "本来入金額",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true} />,
    },
    {
      field: "managementCompanyAmount2",
      headerName: "管理会社入金",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true} />,
    },
    {
      field: "difference2",
      headerName: "差額",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true} showNotZeroBackgroundColor={true} />,
    },
    {
      field: "expectedAmount3",
      headerName: "本来入金額",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true} />,
    },
    {
      field: "managementCompanyAmount3",
      headerName: "管理会社入金",
      headerClassName: "align-right-header",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true}/>,
    },
    {
      field: "difference3",
      headerName: "差額",
      minWidth: 120,
      flex: 1,
      editable: false,
      sortable: false,
      filterable: false,
      renderCell: (params) => <CurrencyCell {...params} showZero={true} showNotZeroBackgroundColor={true} />,
    },
  ];

export type { PropertyIncomeExpenseSummaryRow };